// <auto-generated />
using System;
using Fortuno.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fortuno.Infra.Migrations
{
    [DbContext(typeof(FortunoContext))]
    [Migration("20260420135423_DropWebhookEvents")]
    partial class DropWebhookEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fortuno.Domain.Models.InvoiceReferrer", b =>
                {
                    b.Property<long>("InvoiceReferrerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_referrer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("InvoiceReferrerId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long>("LotteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_id");

                    b.Property<float>("ReferralPercentAtPurchase")
                        .HasColumnType("real")
                        .HasColumnName("referral_percent_at_purchase");

                    b.Property<long>("ReferrerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_user_id");

                    b.HasKey("InvoiceReferrerId")
                        .HasName("fortuna_invoice_referrers_pkey");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasDatabaseName("fortuna_invoice_referrers_invoice_uq");

                    b.HasIndex("ReferrerUserId", "LotteryId")
                        .HasDatabaseName("fortuna_invoice_referrers_referrer_lottery_ix");

                    b.ToTable("fortuna_invoice_referrers", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.Lottery", b =>
                {
                    b.Property<long>("LotteryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("LotteryId"));

                    b.Property<string>("CancelReason")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<long?>("CancelledByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DescriptionMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_md");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.Property<int>("NumberType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("number_type");

                    b.Property<int>("NumberValueMax")
                        .HasColumnType("integer")
                        .HasColumnName("number_value_max");

                    b.Property<int>("NumberValueMin")
                        .HasColumnType("integer")
                        .HasColumnName("number_value_min");

                    b.Property<string>("PrivacyPolicyMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("privacy_policy_md");

                    b.Property<float>("ReferralPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("referral_percent");

                    b.Property<string>("RulesMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rules_md");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<int>("TicketMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ticket_max");

                    b.Property<int>("TicketMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ticket_min");

                    b.Property<long>("TicketNumEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("ticket_num_end");

                    b.Property<long>("TicketNumIni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("ticket_num_ini");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ticket_price");

                    b.Property<decimal>("TotalPrizeValue")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_prize_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("LotteryId")
                        .HasName("fortuna_lotteries_pkey");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("fortuna_lotteries_slug_uq");

                    b.HasIndex("Status")
                        .HasDatabaseName("fortuna_lotteries_status_ix");

                    b.ToTable("fortuna_lotteries", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.LotteryCombo", b =>
                {
                    b.Property<long>("LotteryComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_combo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("LotteryComboId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscountLabel")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("discount_label");

                    b.Property<float>("DiscountValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("discount_value");

                    b.Property<long>("LotteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<int>("QuantityEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity_end");

                    b.Property<int>("QuantityStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity_start");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("LotteryComboId")
                        .HasName("fortuna_lottery_combos_pkey");

                    b.HasIndex("LotteryId");

                    b.ToTable("fortuna_lottery_combos", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.LotteryImage", b =>
                {
                    b.Property<long>("LotteryImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("LotteryImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(260)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<long>("LotteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_id");

                    b.HasKey("LotteryImageId")
                        .HasName("fortuna_lottery_images_pkey");

                    b.HasIndex("LotteryId");

                    b.ToTable("fortuna_lottery_images", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.NumberReservation", b =>
                {
                    b.Property<long>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reservation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ReservationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long>("LotteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_id");

                    b.Property<long>("TicketNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_number");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ReservationId")
                        .HasName("fortuna_number_reservations_pkey");

                    b.HasIndex("LotteryId", "ExpiresAt")
                        .HasDatabaseName("fortuna_number_reservations_lottery_expires_ix");

                    b.HasIndex("UserId", "LotteryId")
                        .HasDatabaseName("fortuna_number_reservations_user_lottery_ix");

                    b.ToTable("fortuna_number_reservations", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.Raffle", b =>
                {
                    b.Property<long>("RaffleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("raffle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RaffleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DescriptionMd")
                        .HasColumnType("text")
                        .HasColumnName("description_md");

                    b.Property<bool>("IncludePreviousWinners")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("include_previous_winners");

                    b.Property<long>("LotteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RaffleDatetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("raffle_datetime");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("video_url");

                    b.HasKey("RaffleId")
                        .HasName("fortuna_raffles_pkey");

                    b.HasIndex("LotteryId");

                    b.ToTable("fortuna_raffles", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.RaffleAward", b =>
                {
                    b.Property<long>("RaffleAwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("raffle_award_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RaffleAwardId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("RaffleId")
                        .HasColumnType("bigint")
                        .HasColumnName("raffle_id");

                    b.HasKey("RaffleAwardId")
                        .HasName("fortuna_raffle_awards_pkey");

                    b.HasIndex("RaffleId", "Position")
                        .IsUnique()
                        .HasDatabaseName("fortuna_raffle_awards_raffle_position_uq");

                    b.ToTable("fortuna_raffle_awards", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.RaffleWinner", b =>
                {
                    b.Property<long>("RaffleWinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("raffle_winner_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RaffleWinnerId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("PrizeText")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnName("prize_text");

                    b.Property<long>("RaffleAwardId")
                        .HasColumnType("bigint")
                        .HasColumnName("raffle_award_id");

                    b.Property<long>("RaffleId")
                        .HasColumnType("bigint")
                        .HasColumnName("raffle_id");

                    b.Property<long?>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("RaffleWinnerId")
                        .HasName("fortuna_raffle_winners_pkey");

                    b.HasIndex("RaffleAwardId");

                    b.HasIndex("TicketId");

                    b.HasIndex("RaffleId", "RaffleAwardId")
                        .IsUnique()
                        .HasDatabaseName("fortuna_raffle_winners_raffle_award_uq");

                    b.ToTable("fortuna_raffle_winners", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.RefundLog", b =>
                {
                    b.Property<long>("RefundLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("refund_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RefundLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ExecutedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("executed_by_user_id");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("varchar(160)")
                        .HasColumnName("external_reference");

                    b.Property<decimal>("ReferenceValue")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("reference_value");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.HasKey("RefundLogId")
                        .HasName("fortuna_refund_logs_pkey");

                    b.HasIndex("TicketId");

                    b.ToTable("fortuna_refund_logs", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TicketId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long>("LotteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_id");

                    b.Property<int>("RefundState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("refund_state");

                    b.Property<long>("TicketNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_number");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TicketId")
                        .HasName("fortuna_tickets_pkey");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("fortuna_tickets_invoice_ix");

                    b.HasIndex("LotteryId", "RefundState")
                        .HasDatabaseName("fortuna_tickets_lottery_refund_ix");

                    b.HasIndex("LotteryId", "TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("fortuna_tickets_lottery_number_uq");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("fortuna_tickets_user_created_ix");

                    b.ToTable("fortuna_tickets", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.TicketOrder", b =>
                {
                    b.Property<long>("TicketOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TicketOrderId"));

                    b.Property<string>("BrCode")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("br_code");

                    b.Property<string>("BrCodeBase64")
                        .HasColumnType("text")
                        .HasColumnName("br_code_base64");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expired_at");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("invoice_number");

                    b.Property<long>("LotteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("lottery_id");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("PickedNumbersJson")
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("picked_numbers_json");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("referral_code");

                    b.Property<float>("ReferralPercentAtPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("referral_percent_at_purchase");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TicketOrderId")
                        .HasName("fortuna_ticket_orders_pkey");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_orders_invoice_id");

                    b.HasIndex("LotteryId")
                        .HasDatabaseName("ix_ticket_orders_lottery_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ticket_orders_user_id");

                    b.ToTable("fortuna_ticket_orders", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.UserReferrer", b =>
                {
                    b.Property<long>("UserReferrerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_referrer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("UserReferrerId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("referral_code");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("UserReferrerId")
                        .HasName("fortuna_user_referrers_pkey");

                    b.HasIndex("ReferralCode")
                        .IsUnique()
                        .HasDatabaseName("fortuna_user_referrers_code_uq");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("fortuna_user_referrers_user_uq");

                    b.ToTable("fortuna_user_referrers", (string)null);
                });

            modelBuilder.Entity("Fortuno.Domain.Models.LotteryCombo", b =>
                {
                    b.HasOne("Fortuno.Domain.Models.Lottery", "Lottery")
                        .WithMany("Combos")
                        .HasForeignKey("LotteryId")
                        .IsRequired()
                        .HasConstraintName("fk_lottery_lottery_combo");

                    b.Navigation("Lottery");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.LotteryImage", b =>
                {
                    b.HasOne("Fortuno.Domain.Models.Lottery", "Lottery")
                        .WithMany("Images")
                        .HasForeignKey("LotteryId")
                        .IsRequired()
                        .HasConstraintName("fk_lottery_lottery_image");

                    b.Navigation("Lottery");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.Raffle", b =>
                {
                    b.HasOne("Fortuno.Domain.Models.Lottery", "Lottery")
                        .WithMany("Raffles")
                        .HasForeignKey("LotteryId")
                        .IsRequired()
                        .HasConstraintName("fk_lottery_raffle");

                    b.Navigation("Lottery");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.RaffleAward", b =>
                {
                    b.HasOne("Fortuno.Domain.Models.Raffle", "Raffle")
                        .WithMany("Awards")
                        .HasForeignKey("RaffleId")
                        .IsRequired()
                        .HasConstraintName("fk_raffle_raffle_award");

                    b.Navigation("Raffle");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.RaffleWinner", b =>
                {
                    b.HasOne("Fortuno.Domain.Models.RaffleAward", "RaffleAward")
                        .WithMany()
                        .HasForeignKey("RaffleAwardId")
                        .IsRequired()
                        .HasConstraintName("fk_raffle_award_raffle_winner");

                    b.HasOne("Fortuno.Domain.Models.Raffle", "Raffle")
                        .WithMany("Winners")
                        .HasForeignKey("RaffleId")
                        .IsRequired()
                        .HasConstraintName("fk_raffle_raffle_winner");

                    b.HasOne("Fortuno.Domain.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .HasConstraintName("fk_ticket_raffle_winner");

                    b.Navigation("Raffle");

                    b.Navigation("RaffleAward");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.RefundLog", b =>
                {
                    b.HasOne("Fortuno.Domain.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("fk_ticket_refund_log");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.Ticket", b =>
                {
                    b.HasOne("Fortuno.Domain.Models.Lottery", "Lottery")
                        .WithMany("Tickets")
                        .HasForeignKey("LotteryId")
                        .IsRequired()
                        .HasConstraintName("fk_lottery_ticket");

                    b.Navigation("Lottery");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.TicketOrder", b =>
                {
                    b.HasOne("Fortuno.Domain.Models.Lottery", "Lottery")
                        .WithMany()
                        .HasForeignKey("LotteryId")
                        .IsRequired()
                        .HasConstraintName("fk_ticket_order_lottery");

                    b.Navigation("Lottery");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.Lottery", b =>
                {
                    b.Navigation("Combos");

                    b.Navigation("Images");

                    b.Navigation("Raffles");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Fortuno.Domain.Models.Raffle", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Winners");
                });
#pragma warning restore 612, 618
        }
    }
}
